In [3]:
import numpy as np

In [4]:
np.__version__

'2.3.1'

In [3]:
randonArr = np.random.rand(3,2,3) 

In [4]:
randonArr

array([[[0.18702556, 0.15732086, 0.71411273],
        [0.01825923, 0.83108046, 0.8952076 ]],

       [[0.29180716, 0.42088217, 0.50089356],
        [0.13116383, 0.85484094, 0.41660007]],

       [[0.21734521, 0.37775771, 0.20148527],
        [0.9929254 , 0.25707478, 0.82451408]]])

In [6]:
randonArr.shape

(3, 2, 3)

In [7]:
randonArr.size

18

In [8]:
randonArr.dtype

dtype('float64')

In [26]:
zeroes = np.zeros((4,2,3))

In [27]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
zeroes.ndim

3

In [29]:
zeroes.size

24

In [21]:
full = np.full((4,2,3),8)

In [22]:
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [30]:
full.ndim

3

In [31]:
ones = np.ones((3,2,3))

In [32]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

# Update & Delete

In [6]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [7]:
a2

array([[[0.62845847, 0.40077967],
        [0.59563091, 0.07776504],
        [0.88140644, 0.60511622]],

       [[0.57889499, 0.55306327],
        [0.75904001, 0.5132563 ],
        [0.47520064, 0.3118693 ]]])

In [8]:
a1

array([[[0.50376003, 0.96753298],
        [0.73417347, 0.26461956],
        [0.59700147, 0.02116195]],

       [[0.16704273, 0.08509921],
        [0.48620187, 0.8229814 ],
        [0.79638071, 0.7592496 ]]])

In [9]:
np.add(a1,a2)

array([[[1.13221849, 1.36831265],
        [1.32980438, 0.3423846 ],
        [1.47840791, 0.62627817]],

       [[0.74593772, 0.63816248],
        [1.24524188, 1.3362377 ],
        [1.27158136, 1.0711189 ]]])

In [10]:
np.subtract(a1,a2)

array([[[-0.12469844,  0.5667533 ],
        [ 0.13854256,  0.18685452],
        [-0.28440497, -0.58395428]],

       [[-0.41185227, -0.46796406],
        [-0.27283814,  0.3097251 ],
        [ 0.32118007,  0.4473803 ]]])

In [11]:
np.divide(a1,a2)

array([[[0.80158046, 2.41412687],
        [1.23259801, 3.40280886],
        [0.67732824, 0.03497171]],

       [[0.28855445, 0.15386886],
        [0.64054841, 1.60345114],
        [1.67588308, 2.43451216]]])

In [12]:
np.multiply(a1, a2)

array([[[0.31659225, 0.38776755],
        [0.43729641, 0.02057815],
        [0.52620094, 0.01280544]],

       [[0.0967002 , 0.04706525],
        [0.36904667, 0.42240039],
        [0.37844063, 0.23678664]]])

In [18]:
 zeroes = np.zeros((3,2,3))

In [19]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
 new_arr = np.ones((3,2,3))

In [21]:
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
app = np.append(zeroes,new_arr, axis=0)

In [33]:
app

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])